# Project Configuration for test-research-project
project:
  name: "test-research-project"
  template: "business-research"
  created: "2025-07-18T21:59:34Z"
  
settings:
  output_directory: "results/"
  log_directory: "logs/"
  data_directory: "data/"
  
template_settings:
  focus: "company_research"
  data_sources:
    - "news_articles"
    - "company_websites"
    - "financial_reports"
  export_formats: ["csv", "json", "excel"]
