# Prometheus Configuration
# Monitoring and metrics collection for Visual Analytics Platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Visual Analytics API Metrics
  - job_name: 'visual-analytics-api'
    static_configs:
      - targets: ['app:9001']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # PostgreSQL Metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    
  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    
  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    
  # Application Performance Monitoring
  - job_name: 'apm'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /api/metrics
    scrape_interval: 30s

remote_write:
  - url: "https://prometheus-remote-write-endpoint"
    basic_auth:
      username: "username"
      password: "password"
