# Prometheus Configuration for Business Intelligence Scraper
# Production Monitoring Setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'business-intelligence-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Business Intelligence Scraper Application
  - job_name: 'bis-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # System metrics (node exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  # Application health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/health'
    scrape_interval: 10s
    scrape_timeout: 5s
