global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scraper API monitoring
  - job_name: 'scraper-api'
    static_configs:
      - targets: ['scraper-api:8000']
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['scraper-redis:6379']

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['scraper-postgres:5432']

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['scraper-nginx:80']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
