version: '3.8'
services:
  api:
    build: ..
    command: uvicorn business_intel_scraper.backend.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  worker:
    build: ..
    command: celery -A business_intel_scraper.backend.workers.tasks.celery_app worker --loglevel=info
    depends_on:
      - api
