version: '3.9'
services:
  api:
    build:
      context: ../../..
      dockerfile: business_intel_scraper/infra/docker/api/Dockerfile
    command: uvicorn business_intel_scraper.backend.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
  worker:
    build:
      context: ../../..
      dockerfile: business_intel_scraper/infra/docker/worker/Dockerfile
    command: celery -A business_intel_scraper.backend.workers.tasks.celery_app worker --loglevel=info
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    depends_on:
      - api
