name: CI

on:
  pull_request:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi starlette httpx sqlalchemy scrapy sse-starlette uvicorn pydantic selenium playwright
      - name: Run tests
        run: pytest -q
